<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ch</string>
		<string>choice</string>
	</array>
	<key>name</key>
	<string>Choice</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(0[0-9]+)|(0[Xx][0-9A-Fa-f]+)|(\d*\.?\d+(?:[Ee](?:[+-]?\d+)?)?)</string>
			<key>name</key>
			<string>constant.numeric.choice</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'([^\\']|\\.)*'</string>
			<key>name</key>
			<string>string.quoted.single.choice</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"([^\\"]|\\.)*"</string>
			<key>name</key>
			<string>string.quoted.double.choice</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|null|undefined)\b|@[0-9]*</string>
			<key>name</key>
			<string>constant.language.choice</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|loop|while|for|break|continue|returns?)\b|-&gt;</string>
			<key>name</key>
			<string>keyword.control.choice</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(typeof|instanceof|in)\b</string>
			<key>name</key>
			<string>keyword.operator.choice</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.double-slash.choice</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.choice</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.choice</string>
		</dict>
		<dict>
			<key>match</key>
			<string>===|!==|\+\+|--|&amp;&amp;|\|\||~|\?|:|(!|\*|/|%|\+|-|&lt;&lt;|&gt;&gt;&gt;?|&lt;|&gt;|&amp;|\^|\||)=?|==|=</string>
			<key>name</key>
			<string>keyword.operator.choice</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.choice</string>
	<key>uuid</key>
	<string>81767a3b-7291-4360-b196-e4f7a516ddd6</string>
</dict>
</plist>
